from django.contrib import admin
from .models import AccessRecord, Age, Compititions, Contect,Customer, Participants, Post, Sports,Strokes, Style,Tag,Product,Order,Swimmers_pool,My_swimming_students,Chartapp,Age,Matplotlib, Topic, Webpage
# Register your models here.
admin.site.register(Contect)
admin.site.register(Customer)
admin.site.register(Strokes)
admin.site.register(Tag)
admin.site.register(Product)
admin.site.register(Order)
admin.site.register(Post)
admin.site.register(Swimmers_pool)
admin.site.register(My_swimming_students)
admin.site.register(Chartapp)
admin.site.register(Age)
admin.site.register(Matplotlib)
admin.site.register(Compititions)
admin.site.register(Participants)
admin.site.register(Sports)
admin.site.register(Style)
admin.site.register(AccessRecord)
admin.site.register(Topic)
admin.site.register(Webpage)
