# Generated by Django 3.2.7 on 2021-09-25 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strokes',
            fields=[
                ('stroke_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=2000)),
                ('swimmer', models.CharField(max_length=2000)),
                ('tags', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('event', models.FileField(upload_to='images')),
            ],
        ),
    ]
