# Generated by Django 3.2.7 on 2021-10-13 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_swimmers_pool'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_swimming_students',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=200)),
                ('student_interest', models.TextField()),
                ('student_favourite_stroke', models.CharField(max_length=13)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
