# Generated by Django 3.2.7 on 2021-10-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_age'),
    ]

    operations = [
        migrations.RenameField(
            model_name='swimmers_pool',
            old_name='swimmer_name',
            new_name='Swiimmingpool_name',
        ),
    ]
