# Generated by Django 3.2.7 on 2021-10-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_swimmer_name_swimmers_pool_swiimmingpool_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matplotlib',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=122)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
