# Generated by Django 3.2.7 on 2021-10-30 06:09

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_matplotlib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compititions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comp', models.ForeignKey(null=True, on_delete=home.models.Compititions, to='home.compititions')),
            ],
        ),
    ]
