# Generated by Django 3.2.7 on 2021-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_compititions_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='comp',
        ),
        migrations.AddField(
            model_name='participants',
            name='comp1',
            field=models.ManyToManyField(to='home.Compititions'),
        ),
    ]
