# Generated by Django 3.2.7 on 2021-10-31 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_sports_style'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='sports',
            new_name='sports_name',
        ),
    ]
